baseURL = "https://affectionate-lichterman-36ce02.netlify.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-sam"

[params]
dateform             = "Mon Jan 02, 2006"
dateformfull         = "Mon Jan 2 2006 15:04:05 EST"